version: '3.8'

services:

  frontend:
    container_name: frontend
    image: node:16.13.0-alpine3.14
    ports:
      - 3000:3000
    working_dir: /var/frontend
    volumes:
      - ./frontend:/var/frontend
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - ganache
    command: npm start

  hardhat:
    container_name: hardhat
    build: ./docker/hardhat
    ports:
      - 8545:8545
    working_dir: /var/hardhat
    volumes:
      - ./:/var/hardhat:cached
    tty: true
    environment:
      - TZ=Asia/Tokyo
    command: npx hardhat node

  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:v6.12.2
    ports:
      - 8545:8545
    volumes:
      - ./volume/ganache:/var/ganache
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/var/ganache/data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug